# password
password: p@ssw0rd

server:
    applicationConnectors:
        - type: http
          port: 8080
        - type: https
          port: 8443
          keyStorePath: dropbookmarks.keystore
          keyStorePassword: p@ssw0rd
          validateCerts: false

database:
    #driverClass, user and url are mandatory
    driverClass: com.mysql.jdbc.Driver
    #note here that root is not best practice and one should create a user
    #user: root
    #password: bananas
    user: liquibaseUser
    password: liquibase
    url: jdbc:mysql://localhost:3306/DropBookmarks


